INSERT INTO USUARIO_ENTITY (ID, NOME, LOGIN, SENHA, EMAIL) VALUES (1, 'Edu1', 'edu1l', '1234', 'edu1@gmal.com');
ALTER SEQUENCE USUARIO_ENTITY_ID_SEQ RESTART WITH 2;

INSERT INTO PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (2, 'Pastor');
INSERT INTO PERFIL (ID, DESCRICAO) VALUES (3, 'Usuário');
ALTER SEQUENCE PERFIL_SEQ RESTART WITH 4;

INSERT INTO RECURSOS (ID, NOME, CHAVE) VALUES (1, 'Tela usuário', 'usuario');
INSERT INTO RECURSOS (ID, NOME, CHAVE) VALUES (2, 'Tela perfil', 'perfil');
INSERT INTO RECURSOS (ID, NOME, CHAVE) VALUES (3, 'Tela recursos', 'recurso');
ALTER SEQUENCE RECURSOS_SEQ RESTART WITH 4;
